Silence TS stricts errors
error: TS7011: Function expression, which lacks return-type annotation, implicitly has an 'any' return type.
The TS compiler is set to strict by tsconfig default option being noImplicitAny
fix: add explicit return type annotations to Promise callbacks